### PR TITLE
Add bullet after modified time entry

### PR DESCRIPTION
**Pull request by dgrammlich**

### CODE REVIEW

**Review by markdumay — COMMENTED** [review]
Thanks for spotting this. I suggest to simplify the code a little:
```
 {{ if ne $datestr $lastmodstr -}}
    &nbsp{{ $lastmodstr | i18n "lastModified" }}
{{ end -}}
&nbsp;&bull;&nbsp;
```

**Comment by dgrammlich** [comment]
There is still a `&nbsp;` missing after the output of `$datestr` that interferes with the leading whitespace of the output of the last modification time. Didn't quite get a solution yet.

```html
{{ $datestr | i18n "postedOnDate" -}}
 {{ if ne $datestr $lastmodstr -}}
   &nbsp;{{ $lastmodstr | i18n "lastModified" }}
{{ end -}}
```

**Comment by markdumay** [comment]
I took another look at this, what about the following code? I removed the parentheses `()` from the language files too, and included them in the below code snippet instead.

```
<small class="text-muted text-uppercase">
    {{ $datestr | i18n "postedOnDate" -}}
    {{ if ne $datestr $lastmodstr -}}&nbsp;({{ $lastmodstr | i18n "lastModified" }}){{ end }} &bull;
    {{ .ReadingTime | lang.FormatNumber 0 }}&nbsp;{{ i18n "minutesShort" }} {{ i18n "read" }} &bull;
    {{ .WordCount | lang.FormatNumber 0 }}&nbsp;{{ i18n "words" }}
</small>
```

**Comment by dgrammlich** [comment]
Hoi Mark, thank you so much for your work and sorry for the delay. I couldn't look into it due to health issues.

I tested it locally and it looks great both with and without modification timestamp. ☺️

**Comment by markdumay** [comment]
Great! Feel free to modify the PR with the updated code, so I can merge your PR with the main repository.

**Review by markdumay — APPROVED** [review]

**Pull request merged**
